apiVersion: v2
name: my-phoenix-app
description: A Helm chart for deploying a Phoenix application
version: 0.1.0
appVersion: 1.6.0
icon: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
