
image:
  repository: anilson87/my-web-app
  tag: latest

service:
  ports:
    - name: http
      port: 8000

env:
  UID: 1000
  GID: 1000
  MIX_ENV: prod
  NODE_ENV: production
  POSTGRES_USER: hello
  POSTGRES_PASSWORD: password
  POSTGRES_DB: hello
  POSTGRES_HOST: postgres
  POSTGRES_HOST: cluster-with-metrics-rw
  POSTGRES_PORT: 5432
  POSTGRES_POOL: 15
  DOCKER_BUILDKIT: 1
  COMPOSE_PROJECT_NAME: hellophoenix
  COMPOSE_PROFILES: postgres,assets,web
  URL_SCHEME: http
  URL_HOST: localhost
  URL_PORT: 8000
  SECRET_KEY_BASE: please_generate_a_more_secure_unique_secret_value_for_your_project

volume:
  mountPath: /app/priv/static
