apiVersion: apps/v1
kind: Deployment
metadata:
  name: js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: js
  template:
    metadata:
      labels:
        app: js
    spec:
      containers:
        - name: js
          image: "anilson87/hellophoenix-js:latest"
          command:
            - "sh"
            - "-c"
#            - "cp /scripts/* /run/"
            - "../run yarn:build:js"
            -  echo "Running JS build commands here"
          env:
            - name: MIX_ENV
              value: "{{ .Values.env.MIX_ENV }}"
            - name: NODE_ENV
              value: "{{ .Values.env.NODE_ENV }}"
            - name: UID
              value: "{{ .Values.env.UID }}"
            - name: GID
              value: "{{ .Values.env.GID }}"
#          restartPolicy: UnlessStopped
#          terminationGracePeriodSeconds: 0
          stdin: true
          stdinOnce: true
          tty: true
#          volumeMounts:
#            - name: js-app-volume
#              mountPath: {{ .Values.volume.js.mountPath}}
#            - name: js-run-volume
#              mountPath: /run
#      volumes:
#        - name: js-app-volume
#          configMap:
#            name: run-script
#        - name: js-run-volume
#          emptyDir: {}
