apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/anilson/hellophoenix/priv/static
    type: DirectoryOrCreate
